version: '3.8'
services:
  backend:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    image: vsaravind01/bert-ner-tagger:0.1.0
    restart: always
    ports:
      - "8000:8000"
    expose:
      - 8000

  frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    image: vsaravind01/bert-ner-tagger:frontend
    restart: always
    ports:
      - "3000:3000"
    expose:
      - 3000