version: '3.8'
services:
  backend:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8000:8000"
    expose:
      - 8000

  frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3000:3000"
    expose:
      - 3000